name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          java-version: 20

      - name: Build with Maven
        run: mvn clean package

      - name: Run Spring Boot Application
        run: java -jar target/your-application.jar
